
function userInput = centeredTextInput(prompt, defaultText)
    % Create a figure window
    fig = figure('Name', prompt, ...
                 'NumberTitle', 'off', ...
                 'Position', [500 400 350 200], ...  % Increased height for spacing
                 'Resize', 'off', ...
                 'WindowStyle', 'modal');

    movegui(fig, 'center');  % Center the figure on the screen

    % Display prompt
    uicontrol('Style', 'text', ...
              'String', prompt, ...
              'Position', [50 140 250 30], ...
              'FontSize', 10, ...
              'FontWeight', 'bold');

    % Input field for user to type values
    inputBox = uicontrol('Style', 'edit', ...
                         'String', defaultText, ...
                         'Position', [50 100 250 30], ...
                         'FontSize', 10, ...
                         'HorizontalAlignment', 'center');

    % OK button to confirm input
    uicontrol('Style', 'pushbutton', ...
              'String', 'OK', ...
              'Position', [50 50 100 30], ...
              'FontSize', 10, ...
              'ForegroundColor', 'green', ...
              'BackgroundColor', 'white', ...
              'FontWeight', 'bold', ...
              'Callback', @okButtonCallback);

    % Styled "Close" button with red border and white text
    uicontrol('Style', 'pushbutton', ...
              'String', 'Close', ...
              'Position', [200 50 100 30], ...
              'FontSize', 10, ...
              'ForegroundColor', 'red', ...
              'BackgroundColor', 'white', ...
              'FontWeight', 'bold', ...
              'Callback', @closeButtonCallback);

    % Wait for user input
    userInput = defaultText;  % Default in case the user does nothing
    uiwait(fig);

    % OK button callback function
    function okButtonCallback(~, ~)
        inputStr = strtrim(inputBox.String);  % Get input and remove extra spaces
        if isempty(inputStr)
            userInput = defaultText;  % If the user enters nothing, return the default
        else
            userInput = inputStr;  % Otherwise, return what they typed
        end
        uiresume(fig);
        close(fig);
    end

    % Close button callback function
    function closeButtonCallback(~, ~)
        disp('User closed the input window. Stopping execution.');
        close(fig);
        error('Execution stopped by user.');
    end
end